//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int ID { get; set; }
        public string COLOR_BOARD { get; set; }
        public string SHAPE_PARENT { get; set; }
        public string SHAPE_CHILD { get; set; }
        public string COLOR_PARENT { get; set; }
        public string COLOR_CHILD { get; set; }
        public string COLOR_PATH { get; set; }
        public string STYLE_PATH { get; set; }
    }
}
