//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindMap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MINDMAPEntities : DbContext
    {
        public MINDMAPEntities()
            : base("name=MINDMAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOARD> BOARDs { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<STORAGE> STORAGEs { get; set; }
        public virtual DbSet<TOPIC> TOPICs { get; set; }
    }
}
