//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOPIC
    {
        public int ID { get; set; }
        public int ID_BOARD { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public string LABEL_TP { get; set; }
        public int POS_X { get; set; }
        public int POS_Y { get; set; }
        public int WIDTH { get; set; }
        public int HEIGHT { get; set; }
        public double SIZE { get; set; }
        public string BACKCOLOR { get; set; }
        public string FORECOLOR { get; set; }
        public string SHAPE { get; set; }
        public int TEXT_SIZE { get; set; }
        public string FONT { get; set; }
        public string STYLE_PATH { get; set; }
        public string COLOR_PATH { get; set; }
        public int SIZE_PATH { get; set; }
    
        public virtual BOARD BOARD { get; set; }
    }
}
